/**
 * Stable, machine-readable outcomes at POS domain boundaries.
 *
 * These values are part of API contract generation 1. Add a value; do not
 * rename or reuse one for a different business fact. A route may choose an
 * HTTP status and operator message, but it may not manufacture a financial,
 * stock or authorization outcome that the owning service has not declared.
 */
export const DOMAIN_CODE = Object.freeze({
    // Shared across workflows — authorization and identity facts that recur
    // wherever a money-releasing action needs a second signature.
    APPROVER_REQUIRED: 'APPROVER_REQUIRED',
    MFA_REQUIRED: 'MFA_REQUIRED',
    INVOICE_NUMBER_REQUIRED: 'INVOICE_NUMBER_REQUIRED',
    INVOICE_NOT_FOUND: 'INVOICE_NOT_FOUND',

    // Sale (backend/services/saleService.js)
    INSUFFICIENT_STOCK: 'INSUFFICIENT_STOCK',
    STOCK_ITEM_INACTIVE: 'STOCK_ITEM_INACTIVE',
    STOCK_LOT_UNAVAILABLE: 'STOCK_LOT_UNAVAILABLE',
    STOCK_PURITY_MISMATCH: 'STOCK_PURITY_MISMATCH',
    ADVANCE_BALANCE_EXCEEDED: 'ADVANCE_BALANCE_EXCEEDED',
    EXCHANGE_CREDIT_INVALID: 'EXCHANGE_CREDIT_INVALID',
    EXCHANGE_CUSTOMER_MISMATCH: 'EXCHANGE_CUSTOMER_MISMATCH',
    EXCHANGE_CREDIT_NOT_APPLIED: 'EXCHANGE_CREDIT_NOT_APPLIED',
    SALE_TENDER_INVALID: 'SALE_TENDER_INVALID',
    SALE_TENDER_TOTAL_MISMATCH: 'SALE_TENDER_TOTAL_MISMATCH',

    // Void (backend/services/saleService.js#voidSale)
    VOID_REASON_INVALID: 'VOID_REASON_INVALID',
    VOID_NOT_ALLOWED: 'VOID_NOT_ALLOWED',
    VOID_DATE_RESTRICTED: 'VOID_DATE_RESTRICTED',
    VOID_AFTER_RETURN: 'VOID_AFTER_RETURN',
    ADVANCE_REVERSAL_UNAVAILABLE: 'ADVANCE_REVERSAL_UNAVAILABLE',
    VOID_ALREADY_PROCESSED: 'VOID_ALREADY_PROCESSED',

    // Return / credit note (backend/services/returnService.js)
    RETURN_MODE_INVALID: 'RETURN_MODE_INVALID',
    RETURN_WEIGHT_INVALID: 'RETURN_WEIGHT_INVALID',
    RETURN_CUSTOMER_PHONE_REQUIRED: 'RETURN_CUSTOMER_PHONE_REQUIRED',
    RETURN_LINE_REQUIRED: 'RETURN_LINE_REQUIRED',
    RETURN_LINE_NOT_FOUND: 'RETURN_LINE_NOT_FOUND',
    RETURN_NO_LINES: 'RETURN_NO_LINES',
    RETURN_PRICING_REFUSED: 'RETURN_PRICING_REFUSED',
    RETURN_ZERO_REFUND: 'RETURN_ZERO_REFUND',

    // Advances (backend/services/advanceService.js)
    ADVANCE_PHONE_INVALID: 'ADVANCE_PHONE_INVALID',
    ADVANCE_AMOUNT_INVALID: 'ADVANCE_AMOUNT_INVALID',
    ADVANCE_NAME_TOO_LONG: 'ADVANCE_NAME_TOO_LONG',
    DUPLICATE_REFERENCE: 'DUPLICATE_REFERENCE',
    ADVANCE_REVIEW_DECISION_INVALID: 'ADVANCE_REVIEW_DECISION_INVALID',
    ADVANCE_ENTRY_NOT_FOUND: 'ADVANCE_ENTRY_NOT_FOUND',
    ADVANCE_ALREADY_REVIEWED: 'ADVANCE_ALREADY_REVIEWED',

    // Gateway payments (backend/services/paymentService.js)
    PAYMENT_AMOUNT_MISMATCH: 'PAYMENT_AMOUNT_MISMATCH',
    PAYMENT_CREDIT_PERSIST_FAILED: 'PAYMENT_CREDIT_PERSIST_FAILED',

    // Old-gold exchange (backend/services/oldGoldService.js)
    OLD_GOLD_EXCHANGE_DISABLED: 'OLD_GOLD_EXCHANGE_DISABLED',
    OLD_GOLD_PHONE_INVALID: 'OLD_GOLD_PHONE_INVALID',
    OLD_GOLD_PURITY_INVALID: 'OLD_GOLD_PURITY_INVALID',
    OLD_GOLD_WEIGHT_INVALID: 'OLD_GOLD_WEIGHT_INVALID',
    OLD_GOLD_RATE_UNAVAILABLE: 'OLD_GOLD_RATE_UNAVAILABLE',
    OLD_GOLD_ZERO_CREDIT: 'OLD_GOLD_ZERO_CREDIT'
});

const KNOWN_CODES = new Set(Object.values(DOMAIN_CODE));

/** A defensive guard for legacy callbacks that historically used `error` as a code. */
export function isDomainCode(value) {
    return typeof value === 'string' && KNOWN_CODES.has(value);
}
